default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: atlas_api_development
  host: localhost
  port: 5432
test:
  <<: *default
  database: atlas_api_test

production:
  <<: *default
  database: atlas_api_production
  username: atlas_api
  password: <%= ENV['ATLAS_API_DATABASE_PASSWORD'] %>
